// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:984707605184:web:a8d48837cda404cac6c325',
    messagingSenderId: '984707605184',
    projectId: 'hostellog-c5df0',
    authDomain: 'hostellog-c5df0.firebaseapp.com',
    storageBucket: 'hostellog-c5df0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:984707605184:android:12be6ed310339458c6c325',
    messagingSenderId: '984707605184',
    projectId: 'hostellog-c5df0',
    storageBucket: 'hostellog-c5df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:984707605184:ios:3d0d799e9b1270aec6c325',
    messagingSenderId: '984707605184',
    projectId: 'hostellog-c5df0',
    storageBucket: 'hostellog-c5df0.firebasestorage.app',
    iosClientId:
        '984707605184-fieil688rqhvnib7dkibsn472t25aoob.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelLog',
  );
}
